param([Parameter(Mandatory)][string]$Output)

$ErrorActionPreference = 'SilentlyContinue'
$sha = (& git rev-parse --short HEAD 2>$null)
if (-not $sha) { $sha = 'nogit' }
$ts = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss')

$content = @"
// AUTO-GENERATED by stamp-build-id.ps1. Do not edit; not tracked in git.
namespace MirrorCameraMod
{
    internal static class BuildInfo
    {
        public const string BuildId = "$sha @ $ts UTC";
    }
}
"@

Set-Content -Path $Output -Value $content -Encoding UTF8
